repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/google/pyink
    rev: 24.10.1
    hooks:
    -   id: pyink
        exclude: _pb2\.py

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        exclude: ^(tests/|test_data/|_pb2\.py)

-   repo: https://github.com/PyCQA/pylint
    rev: v4.0.4
    hooks:
    -   id: pylint
        exclude: _pb2\.py
        args: [--rcfile=.pylintrc]
